language: node_js
sudo: false
node_js:
- '7'
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run e2e
before_deploy:
- npm run release
deploy:
- provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token:
    secure: QiAmOtJ1EbQEQbMrD7tfCV45+ay8sj4ndwg+YeLoLuh7OCQiIJFdFEoY20muDKRBl9VumeJFb5EkTuhC0016Dqyv9BYC31lHhAeGCy/PNDywRNdfs8Y7Nu/Uze2pfp3cEn9zNepZu7qze+6/T86ENL1dYNouwLUlu7uaUJotgFODx3XLWTDAhWFyZsvUVirxtI3boyAmjFw78kQAGcg/VAoD5MXrBobnscikU2o+WssDIuCf8CxeVr8/GlCxb/uyBZDevDm5skr8wmGKKnQ6UGII37f9ZZAWPQWlHwo+2jyn/08e8iGVnl9P5fMNXcloZhLgFKUPEgWmsHGaDzdW3hHE9FYCU54BI4yyKEispgW+j/bm0QSnKho+x7SYHi/2vjPiAHFVO5HbwsVrk44Nc8EihpmxocKV44N5VwI42WkyGf0tqwpISYmiTTj+xxy81cK768EOjPvlyKpKtqTBKljF9QuQf37aqj/0E1QV4VmrCmLG9LQ8LaioIEd/Ae++1zn9dTU/kGiyZLoJBKak2sJkKBHAa2pepcmvN5Da+63C66YSwnV7FWMNzd5uszPOHo8zPkcmxAlJCp3QtAmBAljYQIxwFrAw/yslpmbRti8w/HwmO5cqFqiK4igEPTiKWTRHrKexPAXKOt1QPIVd2RoJFBbl+RYsrSy1a9z7Ba4=
  on:
    branch: master
